project:
  type: website

website:
  title: "Data Analytics"
  navbar:
    left:
    - text: "Capstone Project"
      href: "Take Home Exercises/Take-home-Exercise-2.html"
    - text: "VA Take-Home Exercises"
      menu: 
        - text: "Take Home Exercise 1"
          href: take-home-exercise-1.qmd
        - text: "Take Home Exercise 2"
          href: "Take Home Exercises/Take-home-Exercise-2.html"
        - text: "Take Home Exercise 3"
          href: "Take Home Exercises/Take-home-Exercise-3.html"
        - text: "Take Home Exercise 4"
          href: "Take Home Exercises/Take-home-Exercise-4.html"
    - text: "VA Hands On Exercises"
      menu: 
        - text: "Hands On Exercise 3"
          href: "Hands-On-Exercise/Hands_On_Exercise_3.html"
        - text: "Hands On Exercise 4"
          href: "Hands-On-Exercise/Hands_On_Exercise_4.html"
        - text: "Hands On Exercise 5"
          href: "Hands-On-Exercise/Hands_On_Exercise_5.html"
    - text: "VA In Class Exercises"
      menu:
        - text: "In Class Exercise 2"
          href: "Hands-On-Exercise/In-class-ex-2.html"
        - text: "In Class Exercise 3"
          href: "In-Class-Exercise/In-Class-Ex-03.html"
        - text: "In Class Exercise 4"
          href: "In-Class-Exercise/In-Class-Ex-04.html"
        - text: "In Class Exercise 6"
          href: "In-Class-Exercise/In-Class-Ex-06.html"
        - text: "In Class Exercise 7"
          href: "In-Class-Exercise/In-Class-Ex-07.html"
        - text: "In Class Exercise 8"
          href: "In-Class-Exercise/In-Class-Ex-08.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    font-size: 80%; 

editor: visual

