project:
  type: website

website:
  title: "Visual Analytics"
  navbar:
    left:
    - text: "Exercises"
      menu: 
        - text: "Take Home Exercise 1"
          href: take-home-exercise-1.qmd
        - text: "In Class Exercise 2"
          href: "Hands-On-Exercise/In-class-ex-2.html"
      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    font-size: 80%; 

editor: visual

