project:
  type: website

website:
  title: "Visual Analytics"
  navbar:
    left:
    - text: "Exercises"
      menu: 
        - text: "Take Home Exercise 1"
          href: take-home-exercise-1.qmd
      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

